name : str = str("André Da Silva Aquilau")
age : int = int(10)
weight : float = float(66.0)
money : complex = complex(1_500.00)
hidden : bool = bool(True)
loading : bool = bool(False)
matriz : list = list([10,20,30])
vetor : range = range(50,60,70)
tupla : tuple  = tuple([[10, 20],[30, 40]])
dicionario : dict = dict({"name" : "André"})
conjunto : set = set([1,1])
conjuntoVertor = frozenset([1,1])

print(name)
print(age)
print(weight)
print(money)
print(hidden)
print(loading)
print(matriz)
print(vetor)
print(tupla)
print(dicionario)
print(conjunto)
print(conjuntoVertor)